### ISSUE TITLE
Suggestions for embeds.py

### ISSUE THREAD

**Issue by transistor** [brendacs/rolley-py#3]
**1. Embed() class already available in discord package**

* An [Embed()](http://discordpy.readthedocs.io/en/latest/api.html#embed) class already exists. You use it in `commands.py`. Why create a custom class?

* A custom class makes sense if the existing one is too heavyweight, but I don't believe that applies here.

**2. Use a plain function**

* If you switch to `discord.Embed()`, then you only need a simple function (plus optional wrapper):

```python
import discord
from utils.config import EMBEDS

def _generate_embeds(data):
    """ Returns a list of discord.Embed objects generated from the input data """

    embeds = []
    for datum in data:
        title, descrip = datum
        emb = discord.Embed(title=title, description=descrip)
        embeds.append(emb)
    
    return embeds

def get_embeds():
    """ Directly returns the list of Embed objects """
    
    return _generate_embeds(EMBEDS)
```

**Comment by brendacs** [comment]
Imported embed constant directly to `commands.py` and use in `init` function. Removed need for Embed class and deleted `embeds.py`.
